// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from 'admin/controllers/application'

import RecordsController from 'admin/controllers/records_controller'
application.register('records', RecordsController)

import SidebarController from 'admin/controllers/sidebar_controller'
application.register('sidebar', SidebarController)

import FlashMessageController from 'admin/controllers/flash_message_controller'
application.register('flash-message', FlashMessageController)

import PasswordController from 'admin/controllers/password_controller'
application.register('password', PasswordController)

import PasswordGeneratorController from 'admin/controllers/password_generator_controller'
application.register('password-generator', PasswordGeneratorController)

import CountrySelectController from 'admin/controllers/country_select_controller'
application.register('country-select', CountrySelectController)

import CountriesSelectController from 'admin/controllers/countries_select_controller'
application.register('countries-select', CountriesSelectController)

import AssociationSelectorController from 'admin/controllers/association_selector_controller'
application.register('association-selector', AssociationSelectorController)

import JsonbEditorController from 'admin/controllers/jsonb_editor_controller'
application.register('jsonb-editor', JsonbEditorController)

import PaginationController from 'admin/controllers/pagination_controller'
application.register('pagination', PaginationController)

import KeyboardNavigationController from 'admin/controllers/keyboard_navigation_controller'
application.register('keyboard-navigation', KeyboardNavigationController)

import PositionsController from 'admin/controllers/positions_controller'
application.register('positions', PositionsController)

import PhotoCaptureController from 'admin/controllers/photo_capture_controller'
application.register('photo-capture', PhotoCaptureController)

import FilterableSelectController from 'admin/controllers/filterable_select_controller'
application.register('filterable-select', FilterableSelectController)

import CopyToClipboardController from 'admin/controllers/copy_to_clipboard_controller'
application.register('copy-to-clipboard', CopyToClipboardController)
