default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: scriptures_development
  queue:
    <<: *default
    database: scriptures_development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: scriptures_test

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_production") %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_production") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_production") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_production") %>_cable
    migrations_paths: db/cable_migrate

staging:
  primary: &primary_staging
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_staging") %>
    username: <%= ENV["POSTGRES_USER"] %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
  cache:
    <<: *primary_staging
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_staging") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_staging
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_staging") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_staging
    database: <%= ENV.fetch("POSTGRES_DB", "scriptures_staging") %>_cable
    migrations_paths: db/cable_migrate
